---
config_version: 1
registers:
  v1:
    - name: PWR_DRIVERS
      description: Power stage of the drivers is enabled.
      type: bool
      kind: input
      address: 0
  
    - name: LASER_OK
      description: No obstacle detected by the laser in the field.
      type: bool
      kind: input
      address: 1

    - name: EDM_STATUS
      description: Hardware fault detected; there is a relay malfunction.
      type: states
      kind: input
      base_address: 2
      num_bits: 1
      states:
        - name: fault
          description: Relay is not functioning.
          value: 0b0
        - name: ok
          description: Relay is functioning correctly.
          value: 0b1

    - name: ESTOP_OK
      description: Emergency stop is not pressed.
      type: states
      kind: input
      base_address: 3
      num_bits: 1
      states:
        - name: not_ok
          description: Emergency stop is pressed; system is not allowed to move.
          value: 0b0
        - name: ok
          description: Emergency stop is not pressed; system is allowed to move.
          value: 0b1

    - name: ESTOP_FAULT
      description: Emergency stop button fault detected, camera is not working.
      type: bool
      kind: input
      address: 4

    - name: LASER_MODE
      description: Current operational mode of the laser.
      type: states
      kind: input
      base_address: 5
      num_bits: 2
      bit_order: lsbf # msbf: most significant bit first, lsbf: least significant bit first
      states:
        - name: unknown_00
          description: Unknown state.
          value: 0b00
        - name: laser_on
          description: Laser is enabled.
          value: 0b01
        - name: laser_muted
          description: Laser is disabled.
          value: 0b10
        - name: unknown_11
          description: Unknown state.
          value: 0b11

    - name: WARNING_FIELD_FREE
      description: No obstacle detected in the laser warning field.
      type: bool
      kind: input
      address: 7

    - name: HW_OK
      description: All hardware is functioning correctly.
      type: bool
      kind: input
      address: 8

    - name: BRAKE_ENABLED
      description: Brakes are released and system can move.
      type: bool
      kind: input
      address: 9

    - name: MOTION_ENABLED
      description: Motion is enabled.
      type: bool
      kind: input
      address: 10

    - name: SELECTOR_OK
      description: Selector is reading correctly.
      type: bool
      kind: input
      address: 11

    - name: SAFETY_MODE
      description: Current safety mode of the system.
      type: states
      kind: input
      base_address: 12
      num_bits: 3
      bit_order: lsbf
      states:
        - name: driven_by_special
          description: System is driven by special safety mode.
          value: 0b000
        - name: standard
          description: System is in standard operating mode.
          value: 0b001
        - name: standby
          description: System is in standby mode.
          value: 0b010
        - name: charging
          description: System is in charging mode.
          value: 0b100

    - name: ROVER_MOVING
      description: Rover is moving.
      type: bool
      kind: input
      address: 22

    - name: FRONT_LASER_SAFE_ZONE_FREE
      description: No obstacle detected in the front laser safe zone.
      type: bool
      kind: input
      address: 24

    - name: REAR_LASER_SAFE_ZONE_FREE
      description: No obstacle detected in the rear laser safe zone.
      type: bool
      kind: input
      address: 25

    - name: FRONT_LASER_WARNING_ZONE_FREE
      description: No obstacle detected in the front laser warning zone.
      type: bool
      kind: input
      address: 26

    - name: REAR_LASER_WARNING_ZONE_FREE
      description: No obstacle detected in the rear laser warning zone.
      type: bool
      kind: input
      address: 27

    - name: FRONT_LASER_STATUS
      description: There is communication with the front laser.
      type: bool
      kind: input
      address: 28

    - name: REAR_LASER_STATUS
      description: There is communication with the rear laser.
      type: bool
      kind: input
      address: 29

    - name: FRONT_LASER_CONTAMINATION
      description: Front laser is contaminated.
      type: bool
      kind: input
      address: 30

    - name: REAR_LASER_CONTAMINATION
      description: Rear laser is contaminated.
      type: bool
      kind: input
      address: 31

    - name: REED_ON
      description: Reed switch is activated.
      type: bool
      kind: input
      address: 32

    - name: CHARGING_PADS
      description: Charging pads are enabled.
      type: bool
      kind: input
      address: 33

    - name: ELEVATION_UP
      description: Elevation is moving up.
      type: bool
      kind: input
      address: 34

    - name: ELEVATION_DOWN
      description: Elevation is moving down.
      type: bool
      kind: input
      address: 35

    - name: SPECIAL_SAFETY_MODE
      description: Special safety mode is enabled.
      type: states
      kind: input
      base_address: 36
      num_bits: 2
      bit_order: lsbf
      states:
        - name: unknown_00
          description: System is in normal mode.
          value: 0b00
        - name: corridor
          description: System is in corridor mode.
          value: 0b01
        - name: reduced_speed
          description: System is in reduced speed mode.
          value: 0b10
        - name: unknown_11
          description: System is in normal mode.
          value: 0b11

    - name: SW_EMERGENCY_STOP
      description: Software emergency stop is pressed.
      type: bool
      kind: output
      address: 0

    - name: CHARGE_LATCHING
      description: Set charging pads.
      type: set_reset
      set_address: 8
      reset_address: 9

    - name: CHARGING_BOOLEAN
      description: Charging pads are set.
      type: bool
      kind: output
      address: 26

    - name: BUZZER_BEEP
      description: Buzzer beep.
      type: trigger
      address: 10

    - name: BUZZER_QUICK_BEEP
      description: Buzzer quick beep.
      type: bool
      kind: output
      address: 11

    - name: BRAKE_LATCHING
      description: Latch the brakes.
      type: set_reset
      kind: output
      set_address: 13
      reset_address: 14

    - name: BRAKE_BOOLEAN
      description: Brakes are latched.
      type: bool
      kind: output
      address: 15

    - name: BEEP_MODE
      description: Buzzer beep mode.
      type: states
      kind: output
      base_address: 16
      num_bits: 2
      bit_order: lsbf
      states:
        - name: enabled
          description: Buzzer is enabled on robot movement.
          value: 0b00
        - name: beep
          description: Buzzer beeping is disabled.
          value: 0b01
        - name: beep_safety
          description: Same as enabled, but extra beep on safety violation.
          value: 0b10

    - name: SAFETY_MODE_SET
      description: Set safety mode.
      type: states
      kind: output
      base_address: 32
      num_bits: 2
      bit_order: lsbf
      states:
        - name: standard
          description: Set standard safety mode.
          value: 0b00
        - name: charge
          description: Set charge safety mode.
          value: 0b11

    - name: SPECIAL_SAFETY_MODE_CORRIDOR
      description: Set special safety mode to corridor.
      type: bool
      kind: output
      address: 36

    - name: SPECIAL_SAFETY_MODE_REDUCED_SPEED
      description: Set special safety mode to reduced speed.
      type: bool
      kind: output
      trigger: true
      address: 37
