desired_freq: 25.0

outputs:
  laser_modes: [1, 2]
#
laser_modes:    # custom laser modes
  standard:     #  custom name of the mode
    output: [False, False]   # digital outputs
  dock: # This should be rack. Using robotnik_msgs/LaserMode Dock to avoid creating a new one for now
    output: [False, True]
  docking_station:
    output: [True, True]
  muted:
    output: [True, False]

inputs:
  emergency_stop: 2
  safety_stop: 3

set_digital_outputs_service_name: /robot/robotnik_base_hw/set_digital_output
io_subscriber_name: /robot/robotnik_base_hw/io
lidar_output_paths_subscriber_name: /robot/output_paths

monitoring_cases:
  '0':
    mode: undefined
    case: undefined
    speed_range: undefined
  '1':
    mode: safe
    case: standard
    speed_range: superslow
  '2':
    mode: safe
    case: standard
    speed_range: slow
  '3':
    mode: safe
    case: standard
    speed_range: middle
  '4':
    mode: safe
    case: standard
    speed_range: fast
  '5':
    mode: safe
    case: standard
    speed_range: out_of_range
  '6':
    mode: safe
    case: dock
    speed_range: middle
  '7':
    mode: safe
    case: dock
    speed_range: out_of_range
  '8':
    mode: safe
    case: charge
    speed_range: superslow
  '9':
    mode: safe
    case: charge
    speed_range: slow
  '10':
    mode: safe
    case: charge
    speed_range: out_of_range
  '11':
    mode: overridable
    case: standard
    speed_range: superslow
  '12':
    mode: overridable
    case: standard
    speed_range: slow
  '13':
    mode: overridable
    case: standard
    speed_range: middle
  '14':
    mode: overridable
    case: standard
    speed_range: fast
  '15':
    mode: overridable
    case: standard
    speed_range: out_of_range
  '16':
    mode: overridable
    case: dock
    speed_range: middle
  '17':
    mode: overridable
    case: dock
    speed_range: out_of_range
  '18':
    mode: overridable
    case: charge
    speed_range: superslow
  '19':
    mode: overridable
    case: charge
    speed_range: slow
  '20':
    mode: overridable
    case: charge
    speed_range: out_of_range
  '21':
    mode: maintenance
    case: undefined
    speed_range: undefined
  '22':
    mode: overridable
    case: muted
    speed_range: muted
