global:
  emergency_stop: emergency_stop
  safety_stop: safety_stop

  selector_mode_auto: selector_mode_auto
  selector_mode_manual: selector_mode_manual
  selector_mode_maintenance: selector_mode_maintenance

  laser_mute: laser_mute

watchdog:
  enabled: true
  # std(min,max)
  # 50% duty, period 1400(930,2000)ms, pulse limits (480,920)ms
  period_ms: 1400
  signal_a: watchdog_signal_a
  signal_b: watchdog_signal_b

speed:
  enabled: true
  period_ms: 100
  prefix: speed_bit_

laser:
  default_mode: standard
  modes:
    standard:
      input:
        laser_mode_standard: true
      output:
        laser_mode_standard_legacy_1: false
        laser_mode_standard_legacy_2: false
        laser_mode_standard_legacy_3: false
        laser_mode_standard_legacy_4: false

    charging_station:
      input:
        laser_mode_charging_station: true
      output:
        laser_mode_standard_legacy_1: true
        laser_mode_standard_legacy_2: true
        laser_mode_standard_legacy_3: true
        laser_mode_standard_legacy_4: true

  attributes:
    front_laser:
      detecting_obstacles: front_laser_detecting_obstacles
      contamination: front_laser_contamination_led
      free_warning: front_laser_free_warning

    rear_laser:
      detecting_obstacles: rear_laser_detecting_obstacles
      contamination: rear_laser_contamination_led
      free_warning: rear_laser_free_warning
