#!/usr/bin/env python3

import rclpy

from safety_module.safety_module_ros2 import SafetyModuleNode

def main(args=None):
    rclpy.init(args=args)
    safety_module = SafetyModuleNode()
    rclpy.spin(safety_module)

if __name__ == '__main__':
    main()
