#! /usr/bin/env python3

import os
import importlib


def detect_ros_version():
    if 'ROS_VERSION' in os.environ:
        return os.environ['ROS_VERSION']
    raise Exception('ROS_VERSION environment variable not set')

if __name__ == '__main__':
    ros_version = detect_ros_version()
    if ros_version == '1':
        main = importlib.import_module('safety_module.safety_module_ros')
        main.run()
        
    elif ros_version == '2':
        main = importlib.import_module('safety_module.safety_module_ros2')
        main.run()
        
    else:
        raise Exception('Unknown ROS_VERSION: {}'.format(ros_version))        
