<?xml version="1.0"?>
<?xml-model
  href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>safety_module</name>
  <version>0.1.0</version>
  <description>
    The safety_module package.
  </description>
  <maintainer email="rnavarro@robotnik.es">Román Navarro</maintainer>
  <license>BSD</license>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>

  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>sensor_msgs</depend>
  <depend>robotnik_msgs</depend>
  <depend>robotnik_safety_msgs</depend>

  <depend condition="$ROS_VERSION == 2">rclpy</depend>

  <test_depend condition="$ROS_VERSION == 2">ament_cmake_pytest</test_depend>
  <test_depend condition="$ROS_VERSION == 2">ament_cmake_pycodestyle</test_depend>
  <test_depend condition="$ROS_VERSION == 2">ament_lint_auto</test_depend>
  <test_depend condition="$ROS_VERSION == 2">ament_lint_common</test_depend>
  <test_depend condition="$ROS_VERSION == 2">python3-pytest</test_depend>

  <export>
    <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
  </export>
</package>
