---
config_version: 1
registers:
  v1:
    - name: PWR_DRIVERS
      description:
        short: Enables the power stage of the drivers, allowing the robot to move.
        values:
          - "false": Power stage is disabled.
          - "true": Power stage is enabled.
      type: bool
      kind: input
      address: 0

    - name: LASER_OK
      description:
        short: Indicates if the laser detected any obstacles in its field.
        values:
          - "false": Obstacle detected.
          - "true": No obstacle detected or laser safety is off.
      type: bool
      kind: input
      address: 1

    - name: EDM_STATUS
      description:
        short: Any relay malfunctions that could affect system safety.
        values:
          - "fault": Any relay malfunction.
          - "ok": All relays are working correctly.
      type: states
      kind: input
      base_address: 2
      num_bits: 1
      states:
        - name: fault
          value: 0b0
        - name: ok
          value: 0b1

    - name: ESTOP_OK
      description:
        short: Indicates if the emergency stop button is pressed.
        values:
          - "false": Emergency stop is pressed, need to reset.
          - "true": Emergency stop is not pressed and system is operational.
      type: bool
      kind: input
      address: 3

    - name: ESTOP_FAULT
      description:
        short: Indicates if the emergency stop button is faulty.
        values:
          - "false": Emergency stop button is working.
          - "true": Emergency stop button fault detected, camera is not working.
      type: bool
      kind: input
      address: 4

    - name: LASER_MODE
      description:
        short: Current operational mode of the laser.
        values:
          - "laser_on": Safety laser is enabled and is monitoring the area.
          - "laser_muted": Safety laser is muted and not monitoring the area.
      type: states
      kind: input
      base_address: 5
      num_bits: 2
      bit_order: lsbf
      states:
        - name: laser_on
          value: 0b01
        - name: laser_muted
          value: 0b10

    - name: WARNING_FIELD_FREE
      description:
        short: Indicates if the laser detected any obstacles in its warning field.
        values:
          - "false": Obstacle detected.
          - "true": No obstacle detected in the laser warning field.
      type: bool
      kind: input
      address: 7

    - name: HW_OK
      description:
        short: Indicates if all hardware is working correctly.
        values:
          - "false": Hardware malfunction detected.
          - "true": All hardware is working correctly.
      type: bool
      kind: input
      address: 8

    - name: BRAKE_ENABLED
      description:
        short: Indicates if the brakes are released and the system can move.
        values:
          - "false": Brakes are latched.
          - "true": Brakes are released.
      type: bool
      kind: input
      address: 9

    - name: MOTION_ENABLED
      description:
        short: Indicates if the robot is allowed to move.
        values:
          - "false": Robot is not allowed to move.
          - "true": Robot is allowed to move.
      type: bool
      kind: input
      address: 10

    - name: SELECTOR_OK
      description:
        short: Indicates if the selector is reading correctly.
        values:
          - "false": Selector is not reading correctly.
          - "true": Selector is reading correctly.
      type: bool
      kind: input
      address: 11

    - name: SAFETY_MODE
      description:
        short: Current laser safety mode.
        values:
          - "standard": Check SPECIAL_SAFETY_MODE for sub state.
          - "standby": Fields are set to standby mode (deprecated).
          - "charging": Fields are set to charging mode.
      type: states
      kind: input
      base_address: 12
      num_bits: 3
      bit_order: lsbf
      states:
        - name: standard
          value: 0b001
        - name: standby
          value: 0b010
        - name: charging
          value: 0b100

    - name: ROVER_MOVING
      description:
        short: Indicates if the robot is moving.
        values:
          - "false": Robot is zero speed.
          - "true": Robot is moving.
      type: bool
      kind: input
      address: 22

    - name: FRONT_LASER_SAFE_ZONE_FREE
      description:
        short: Indicates if the front laser safe zone is free of obstacles.
        values:
          - "false": Obstacle detected in the front laser safe zone.
          - "true": No obstacle detected in the front laser safe zone.
      type: bool
      kind: input
      address: 24

    - name: REAR_LASER_SAFE_ZONE_FREE
      description:
        short: Indicates if the rear laser safe zone is free of obstacles.
        values:
          - "false": Obstacle detected in the rear laser safe zone.
          - "true": No obstacle detected in the rear laser safe zone.
      type: bool
      kind: input
      address: 25

    - name: FRONT_LASER_WARNING_ZONE_FREE
      description:
        short: Indicates if the front laser warning zone is free of obstacles.
        values:
          - "false": Obstacle detected in the front laser warning zone.
          - "true": No obstacle detected in the front laser warning zone.
      type: bool
      kind: input
      address: 26

    - name: REAR_LASER_WARNING_ZONE_FREE
      description:
        short: Indicates if the rear laser warning zone is free of obstacles.
        values:
          - "false": Obstacle detected in the rear laser warning zone.
          - "true": No obstacle detected in the rear laser warning zone.
      type: bool
      kind: input
      address: 27

    - name: FRONT_LASER_STATUS
      description:
        short: Indicates if there is communication with the front laser.
        values:
          - "false": No communication with the front laser.
          - "true": Communication with the front laser.
      type: bool
      kind: input
      address: 28

    - name: REAR_LASER_STATUS
      description:
        short: Indicates if there is communication with the rear laser.
        values:
          - "false": No communication with the rear laser.
          - "true": Communication with the rear laser.
      type: bool
      kind: input
      address: 29

    - name: FRONT_LASER_CONTAMINATION
      description:
        short: Indicates if the front laser is contaminated.
        values:
          - "false": Front laser is not contaminated.
          - "true": Front laser is contaminated.
      type: bool
      kind: input
      address: 30

    - name: REAR_LASER_CONTAMINATION
      description:
        short: Indicates if the rear laser is contaminated.
        values:
          - "false": Front laser is not contaminated.
          - "true": Front laser is contaminated.
      type: bool
      kind: input
      address: 31

    - name: REED_ON
      description:
        short: Indicates if the reed switch is on, meaning the robot can charge with the pads.
        values:
          - "false": Charging station is not detected.
          - "true": Charging station is detected and robot can charge with the pads.
      type: bool
      kind: input
      address: 32

    - name: CHARGING_PADS
      description:
        short: Indicates if the robot is charging.
        values:
          - "false": Robot is not charging through the pads.
          - "true": REED_ON is detected and robot is charging with charging station.
      type: bool
      kind: input
      address: 33

    - name: ELEVATION_DOWN
      description:
        short: If robot has elevation, indicates the elevation position is down.
        values:
          - "false": Position is not down.
          - "true": Position is down.
      type: bool
      kind: input
      address: 34

    - name: ELEVATION_UP
      description:
        short: If robot has elevation, indicates the elevation position is raised.
        values:
          - "false": Position is not raised.
          - "true": Position is raised.
      type: bool
      kind: input
      address: 35

    - name: SPECIAL_SAFETY_MODE
      description:
        short: Sub state of the standard safety mode.
        values:
          - "standard": The fields grows depending on the speed.
          - "corridor": The fields are reduced on the sides.
          - "reduced_speed": The fields are reduced and the speed is limited. Automatically switches to standard after a while.
      type: states
      kind: input
      base_address: 36
      num_bits: 2
      bit_order: lsbf
      states:
        - name: standard
          value: 0b00
        - name: corridor
          value: 0b01
        - name: reduced_speed
          value: 0b10

    - name: KEY_MODES
      description:
        short: Indicates the current mode of the robot, key selector.
        values:
          - "auto": Key selector is in auto mode.
          - "manual": Key selector is in manual mode.
          - "maintenance": Key selector is in maintenance mode.
      type: states
      kind: input
      base_address: 40
      num_bits: 3
      bit_order: lsbf
      states:
        - name: auto
          value: 0b001
        - name: manual
          value: 0b010
        - name: maintenance
          value: 0b100

    - name: KEY_LASER_MUTE
      description:
        short: Indicates if the laser is muted by the key selector.
        values:
          - "false": Laser is not muted.
          - "true": Laser is muted.
      type: bool
      kind: input
      address: 43

    - name: RESTART_REQUIRED
      description:
        short: Indicates if the robot is in safe state but needs a restart.
        values:
          - "false": Robot safety state ok.
          - "true": Robot is in safe state but needs a restart. Press the blue button.
      type: bool
      kind: input
      address: 44

    - name: SW_EMERGENCY_STOP
      description:
        short: Software emergency stop.
        values:
          - "false": To release the software emergency stop.
          - "true": To activate the software emergency stop.
      type: bool
      kind: output
      address: 0

    - name: CHARGE_LATCHING
      description:
        short: Switches charging pads to enable charging. Applied an OR operation with CHARGING_BOOLEAN.
        values:
          - "set": Enables charging pads.
          - "reset": Disables charging pads.
      type: set_reset
      kind: output
      set_address: 8
      reset_address: 9

    - name: CHARGING_BOOLEAN
      description:
        short: Switches charging pads to enable charging. Applied an OR operation with CHARGE_LATCHING.
        values:
          - "false": Disables charging pads.
          - "true": Enables charging pads.
      type: bool
      kind: output
      address: 26

    - name: BUZZER_BEEP
      description:
        short: Set the buzzer to beep once.
        values:
          - "false": Nothing
          - "true": Beep for 1 second.
      type: trigger
      kind: output
      address: 10

    - name: BUZZER_QUICK_BEEP
      description:
        short: Set the buzzer to beep quickly.
        values:
          - "false": Stop beeping.
          - "true": Beep quickly.
      type: bool
      kind: output
      address: 11

    - name: BRAKE_LATCHING
      description:
        short: Switches the brakes to enable movement. Applied an OR operation with BRAKE_BOOLEAN.
        values:
          - "set": Latches the brakes.
          - "reset": Releases the brakes.
      type: set_reset
      kind: output
      set_address: 13
      reset_address: 14

    - name: BRAKE_BOOLEAN
      description:
        short: Switches the brakes to enable movement. Applied an OR operation with BRAKE_LATCHING.
        values:
          - "false": Releases the brakes.
          - "true": Latches the brakes.
      type: bool
      kind: output
      address: 15

    - name: BEEP_MODE
      description:
        short: Set the buzzer mode.
        values:
          - "enabled": Buzzer is enabled on robot movement.
          - "beep": Buzzer beeping is disabled.
          - "beep_safety": Same as enabled, but extra beep on safety violation.
      type: states
      kind: output
      base_address: 16
      num_bits: 2
      bit_order: lsbf
      states:
        - name: enabled
          value: 0b00
        - name: beep
          value: 0b01
        - name: beep_safety
          value: 0b10

    - name: SAFETY_MODE_SET
      description:
        short: Set the safety mode.
        values:
          - "standard": See SPECIAL_SAFETY_MODE for sub state.
          - "charge": Set charge safety mode.
      type: states
      kind: output
      base_address: 32
      num_bits: 2
      bit_order: lsbf
      states:
        - name: standard
          value: 0b00
        - name: charge
          value: 0b11

    - name: SPECIAL_SAFETY_MODE_CORRIDOR
      description:
        short: Set special safety mode to corridor.
        values:
          - "false": Set to standard safety mode.
          - "true": Set special safety mode to corridor.
      type: bool
      kind: output
      address: 36

    - name: SPECIAL_SAFETY_MODE_REDUCED_SPEED
      description:
        short: Set special safety mode to reduced speed.
        values:
          - "false": Set to standard safety mode.
          - "true": Set special safety mode to reduced speed.
      type: bool
      kind: output
      trigger: true
      address: 37
